const skb = new (require('skb'))('eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1OTVmZTI5NDdkMWEzMTAwMTFhMjFjNmEiLCJ1c2VybmFtZSI6ImV4c3Ryb21pbmVyQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNDk5NDU2MjQ2fQ.dyHLkwQNxt0jrezFHLl06P0le1FBpackZyszEYErY78');

skb.taskHelloWorld('Hello World');
